[build]
command = 'hugo'
publish = 'public'
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = '0.140.1'
GIT_SUBMODULES_PATHS = "themes"
GIT_SUBMODULES_RECURSIVE = true 

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
